kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-snapshot-controller-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: csi-snapshot-controller
    namespace: ${CONTROLPLANE_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-snapshot-controller-clusterrole
