apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-snapshot-webhook-clusterrole
rules:
- apiGroups:
  - groupsnapshot.storage.k8s.io
  resources:
  - volumegroupsnapshots
  - volumegroupsnapshotclasses
  - volumegroupsnapshotcontents
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
